---
title: "Getting-and-Cleaning-Data-Week-4-Assignment"
output:tidydata2.txt
author: Chen Liwei
---


```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())

```

Now, we're preparing our data for the codebook.

```{r prepare_codebook}
library(codebook)
codebook_data <- codebook::bfi

tidydata2<-read.table("./data/tidydata2.txt")

```


Create codebook

```{r codebook}
#The run_analysis.R script performs the data preparation and then followed by the 5 steps required as described in the course assignment.
#the final dataset "tidydata2.txt" is a second, independent tidy dataset with teh average of each variable for each activity and each subject.

#1. Download the dataset, Merges the training and the test sets to create one data set.
#1.1 Dataset was downloaded and extracted under folder "UCI HAR Dataset"

#1.2. read data table and assign varibles.
#read data
### training data

x_train<-read.table("./data/UCI HAR Dataset/train/X_train.txt")  #7352 rows, 561 columns
y_train<-read.table("./data/UCI HAR Dataset/train/Y_train.txt")  #7352 rows, 1 columns
subject_train<-read.table("./data/UCI HAR Dataset/train/subject_train.txt") #7352 rows, 1 column


###  testing datasets
x_test<-read.table("./data/UCI HAR Dataset/test/X_test.txt")   #2947 rows, 561 columns
y_test<-read.table("./data/UCI HAR Dataset/test/Y_test.txt")   #2947 rows, 1 columns
subject_test<-read.table("./data/UCI HAR Dataset/test/subject_test.txt")  #2947 rows, 1 column


### feature vector
features<-read.table("./data/UCI HAR Dataset/features.txt")  #561 rows, 2 columns


###1.3 merge the training and test sets to create one data set

#allx (10299 rows, 561 columns) is created by merging x_train and x_test using rbind() function
#ally (10299 rows, 1 column) is created by merging y_train and y_test using rbind() function
#allsubject (10299 rows, 1 column) is created by merging subject_train and subject_test using rbind() function
#datacombine (10299 rows, 563 column) is created by merging allsubject, ally and allx using cbind() function





###2. Extracts only the measurements on the mean and standard deviation for each measurement. 

#subsetdata (10299 rows, 88 columns) is created by subsetting datacombine, selecting only columns: subject, code and the measurements on the mean and standard deviation (std) for each measurement
##2.1 reading column names
colname<-names(datacombine)

##2.2subset the data frame datacombine by selected names of featuress
subdata<-grep("mean|std",colname)
subdatanames<-features$V2[subdata]
subdatanames<-c(subdatanames,"subject","activity")
subsetdata<-subset(datacombine,select=subdatanames)

str(subsetdata)


##3. Uses descriptive activity names to name the activities in the data set

### read activity labels

activitylabels<-read.table("./data/UCI HAR Dataset/activity_labels.txt")
colnames(activitylabels)<-c("activity","activitytype")

##merge datacombine and activitylabels
datacombine.withactivitynames<-merge(datacombine,activitylabels,by="activity")

## check data

str(datacombine.withactivitynames)
colnames(datacombine.withactivitynames)
head(datacombine.withactivitynames$activitytype,6)

##4.Appropriately labels the data set with descriptive variable names. 


### use gsub editing text variables 
names(datacombine.withactivitynames)<-gsub("^t", "time", names(datacombine.withactivitynames))
names(datacombine.withactivitynames)<-gsub("^f", "frequency", names(datacombine.withactivitynames))
names(datacombine.withactivitynames)<-gsub("Acc", "Accelerometer", names(datacombine.withactivitynames))
names(datacombine.withactivitynames)<-gsub("Gyro", "Gyroscope", names(datacombine.withactivitynames))
names(datacombine.withactivitynames)<-gsub("Mag", "Magnitude", names(datacombine.withactivitynames))
names(datacombine.withactivitynames)<-gsub("BodyBody", "Body", names(datacombine.withactivitynames))

## check

names(datacombine.withactivitynames)

#install.packages("plyr")
library(plyr)

#### 5. From the data set in step 4, creates a second, independent tidy data set with the average 
### of each variable for each activity and each subject

#make a second tidy dataset  (contains 180 rows and 480 variables)
tidydata2<- aggregate(.~subject+activitytype,datacombine.withactivitynames,mean)

tidydata2<-tidydata2[order(tidydata2$subject,tidydata2$activitytype),]

###write table and export

write.table(tidydata2, "./data//UCI HAR Dataset/tidydata2.txt", row.names=FALSE)
  

```
